### ISSUE TITLE
Unable to download from private repository on devel stage

### ISSUE THREAD

**Issue by HviorForgeFlow** [Tecnativa/doodba-scaffolding#12]
On addons.yaml I create an entry for a private repository.
```yaml
./eficent-website:
    defaults:
        depth: $DEPTH_DEFAULT
    remotes:
        Eficent: git+ssh://git@gitlab.com/Eficent/eficent-website.git
    target:
        Eficent $ODOO_VERSION
    merges:
        - Eficent $ODOO_VERSION
```
When ```docker-compose -f setup-devel.yaml run --rm odoo``` is running on background is asking to generate an ssh key for /root/.ssh/id_rsa

What am I doing wrong?

I have an ssh key for pull it.
