### ISSUE TITLE
Improvement to staging/production compose files

### ISSUE THREAD

**Issue by gdgellatly** [Tecnativa/doodba-scaffolding#14]
Hi @Yajo ,

One thing I noticed is that running a command such as `/opt/bin/docker-compose run --rm odoo psql` where traefik labels are configured causes the web interface to become inaccessible (v12.0/pg11.1).

If you can reproduce, maybe something like this for the proxied compose configurations? which seems to work for me. Just removing the traefik labels. Not sure if this is a clean extendable way to do it. I just cut and paste and changed startup and labels.

```
    odoo_internal:
        extends:
            file: common.yaml
            service: odoo
        environment:
            <same as odoo environment stanza>
        restart: unless-stopped
        depends_on:
            - db
            - smtp
        networks:
            default:
            globalwhitelist_shared:
            inverseproxy_shared:
        command:
            - odoo
            - --workers=0
```
